graph TD
    A[Usuario accede a Vacantes Guardadas] --> B[Consultar la lista de vacantes guardadas del usuario];
    B --> C[Mostrar la lista de vacantes guardadas con información relevante título, Secretaría, ubicación, fecha de publicación];
    C --> D[Permitir al usuario ver el detalle de cada vacante];
    D --> E[Permitir al usuario eliminar vacantes de la lista I.5.3];
    E --> F[Fin];