graph TD
    A[Reclutador visualiza la vista previa o el perfil de un candidato] --> B[Mostrar opción para contactar];
    B --> C[Abrir interfaz de mensajería similar a II.4.7];
    C --> D[Reclutador escribe y envía mensaje al candidato];
    D --> E[Guardar mensaje en la base de datos asociado al candidato y reclutador];
    E --> F[Enviar notificación al candidato sobre el nuevo mensaje a través de la plataforma y/o correo electrónico];
    F --> G[Mostrar mensaje de Mensaje enviado];
    G --> H[Volver a la lista de candidatos/perfil];
    H --> I[Fin Contacto];