graph TD
    A[Administrador accede a 'Gestión de Vacantes'] --> B[Mostrar lista de todas las vacantes];
    B --> C[Administrador selecciona una o varias vacantes];
    C --> D[Administrador selecciona acción 'Destacar'];
    D --> E[Actualizar el estado de la vacante a 'destacada' y posiblemente establecer duración];
    E --> F[Mostrar mensaje de éxito];
    F --> G[Fin Destacar Vacante];