graph TD
    A[Administrador accede a 'Gestión de Vacantes'] --> B[Consultar la base de datos de vacantes];
    B --> C[Mostrar lista de todas las vacantes con información relevante título, secretaría, estado, fecha de publicación];
    C --> D[Permitir filtrar/buscar vacantes];
    D --> E[Permitir ver detalles de la vacante];
    E --> F[Fin Ver Vacantes];