graph TD
    A[Inicio Validación] --> B{¿Campos obligatorios de secretaría vacíos?};
    B -- Sí --> C[Mostrar error: Campos obligatorios de secretaría];
    B -- No --> D{¿Formato incorrecto en info. secretaría ej. RFC, sitio web?};
    D -- Sí --> E[Mostrar error: Formato incorrecto en secretaría];
    D -- No --> F{¿Campos obligatorios de reclutador vacíos?};
    F -- Sí --> G[Mostrar error: Campos obligatorios de reclutador];
    F -- No --> H{¿Formato incorrecto en info. reclutador ej. correo};
    H -- Sí --> I[Mostrar error: Formato incorrecto en reclutador];
    H -- No --> J[Validación Exitosa];
    C --> J;
    E --> J;
    G --> J;
    I --> J;
    J --> K[Fin Validación];
    
    
    %% comentarios

    %% II.1.5 Aprobación de Cuenta por Administrador: Este proceso se realiza en la interfaz del administrador y no tiene un flujo directo desde la perspectiva del reclutador en este momento. Se mencionó en el flujo de registro (II.1.1).