graph TD
    A[Reclutador selecciona un candidato de la lista de postulaciones] --> B[Consultar la base de datos del perfil del candidato];
    B --> C[Mostrar toda la información del perfil del candidato datos personales, CV completo, etc.];
    C --> D[Volver a la lista de postulaciones];
    D --> E[Fin Ver Perfil];