graph TD
    A[Reclutador selecciona una vacante publicada] --> B[Consultar la base de datos de postulaciones para esa vacante];
    B --> C[Obtener lista de postulaciones con información relevante del candidato nombre, fecha de postulación, vista previa del CV];
    C --> D[Mostrar la lista de postulaciones];
    D --> E[Permitir filtrar postulaciones II.4.2];
    D --> F[Permitir ordenar postulaciones II.4.3];
    D --> G[Permitir ver perfil completo del candidato II.4.4];
    D --> H[Permitir cambiar estado de postulación II.4.5];
    D --> I[Permitir enviar mensajes al candidato II.4.7];
    D --> J[Permitir descargar CV del candidato II.4.8];
    J --> K[Fin Ver Postulaciones];