graph TD
    A[Usuario confirma postulación] --> B[Obtener fecha y hora actual del sistema];
    B --> C[Guardar la postulación con el CV seleccionado, carta si aplica, fecha y hora];
    C --> D[Pasar al envío de notificaciones I.4.4];
    D --> E[Fin];