graph TD
    A[Postulación registrada] --> B[Obtener correo electrónico del interesado];
    B --> C[Obtener información de la vacante];
    C --> D[Generar correo de confirmación para el interesado];
    D --> E[Enviar correo de confirmación al interesado I.6.1.3];
    E --> F[Obtener correo electrónico del reclutador responsable de la vacante];
    F --> G[Generar correo de notificación de nueva postulación para el reclutador];
    G --> H[Enviar correo de notificación al reclutador];
    H --> I[Fin];