graph TD
    A[Administrador visualiza un reporte] --> B[Mostrar opciones de exportación PDF, Excel];
    B --> C[Administrador selecciona formato de exportación];
    C --> D[Generar el archivo del reporte en el formato seleccionado];
    D --> E[Ofrecer la descarga del archivo al administrador];
    E --> F[Fin Exportar Reporte];