graph TD
    A[Administrador accede a 'Reportes y Estadísticas'] --> B[Selecciona 'Número de Postulaciones Recibidas'];
    B --> C[Consultar la base de datos de postulaciones];
    C --> D[Contar postulaciones totales y por vacante];
    D --> E[Mostrar reporte con los conteos];
    E --> F[Permitir personalizar reporte III.4.4];
    F --> G[Permitir exportar reporte III.4.5];
    G --> H[Fin Reporte Postulaciones];
    