graph TD
    A[Administrador visualiza un reporte] --> B[Mostrar opciones de personalización seleccionar rango de fechas, categorías, secretarías, etc.];
    B --> C[Administrador selecciona criterios de personalización];
    C --> D[Generar nuevamente el reporte con los criterios seleccionados];
    D --> E[Mostrar reporte personalizado];
    E --> F[Fin Personalización];