graph TD
    A[Administrador accede a 'Reportes y Estadísticas'] --> B[Selecciona 'Número de Vacantes Publicadas'];
    B --> C[Consultar la base de datos de vacantes];
    C --> D[Contar vacantes totales, por categoría y por secretaría];
    D --> E[Mostrar reporte con los conteos];
    E --> F[Permitir personalizar reporte III.4.4];
    F --> G[Permitir exportar reporte 'III.4.5'];
    G --> H[Fin Reporte Vacantes];