graph TD
    A[Administrador accede a 'Reportes y Estadísticas'] --> B[Selecciona 'Número de Usuarios Registrados'];
    B --> C[Consultar la base de datos de usuarios];
    C --> D[Contar número de interesados y reclutadores];
    D --> E[Mostrar reporte con el conteo];
    E --> F[Permitir exportar reporte III.4.5];
    F --> G[Fin Reporte Usuarios];