graph TD
    A[Inicio Crear/Editar Perfil] --> B{¿Reclutador autenticado?};
    B -- Sí --> C[Mostrar formulario de perfil de la secretaría campos vacíos o con datos existentes];
    C --> D{¿Reclutador guarda o actualiza información?};
    D -- Sí --> E[Validar información del perfil II.2.2];
    E -- Datos válidos --> F[Guardar/Actualizar información del perfil en la base de datos];
    F --> G[Mostrar mensaje de Perfil de la secretaría guardado exitosamente];
    D -- No --> H[¿Reclutador añade/modifica logotipo?];
    H -- Sí --> I[Permitir carga/edición de logotipo];
    I --> F;
    B -- No --> J[Redirigir a página de inicio de sesión];
    G --> K[Fin Crear/Editar Perfil];
    J --> K;
    H -- No --> K;