graph TD
    A[Inicio Validación Perfil] --> B{¿Nombre de la secretaría vacío?};
    B -- Sí --> C[Mostrar error: Nombre de la secretaría es obligatorio];
    B -- No --> D{¿Sitio web con formato incorrecto?};
    D -- Sí --> E[Mostrar error: Formato de sitio web incorrecto];
    D -- No --> F{¿Ubicación estado, municipio vacía};
    F -- Sí --> G[Mostrar error: La ubicación es obligatoria];
    F -- No --> H[¿Tamaño de la secretaría no valido?];
    H -- Sí --> I[Mostrar error: Tamaño de la secretaría no válido];
    H -- No --> J[¿Sector vacío?];
    J -- Sí --> K[Mostrar error: El sector es obligatorio];
    J -- No --> L[Validación Exitosa];
    C --> L;
    E --> L;
    G --> L;
    I --> L;
    K --> L;
    L --> M[Fin Validación Perfil];