graph TD
    A[Mostrar Filtros] --> B{Categoría de trabajo};
    B --> C{Ubicación estado, municipio};
    C --> D{Salario rango};
    D --> E{Nivel de experiencia};
    E --> F{Fecha de publicación};
    F --> G[Aplicar Filtros];